### ISSUE TITLE
Thread safety issue with `SIMIX_process_cleanup()`

### ISSUE THREAD

**Issue by randomstuff** [mquinson/simgrid#19]
While trying to find the root cause of the occasional failure of the kademlia test, I found a thread-safety issue:

<pre>#7  0x00007ffff79a9b6d in xbt_swag_remove (obj=0x61c2c0, swag=0x60d9b0) at /home/corona/workspace/simgrid/src/xbt/swag.c:141
#8  0x00007ffff78878a9 in SIMIX_process_cleanup (process=0x61c2c0) at /home/corona/workspace/simgrid/src/simix/smx_process.c:96
#9  0x00007ffff78473a5 in MSG_process_cleanup_from_SIMIX (smx_proc=0x61c2c0) at /home/corona/workspace/simgrid/src/msg/msg_process.c:52
#10 0x00007ffff7877ed8 in smx_ctx_base_stop (context=0x61c410) at /home/corona/workspace/simgrid/src/simix/smx_context_base.c:89
#11 0x00007ffff797d31f in smx_ctx_sysv_stop_parallel (context=0x61c410) at /home/corona/workspace/simgrid/src/simix/smx_context_sysv.c:242
#12 0x00007ffff797d0bd in smx_ctx_sysv_wrapper (first=6407184) at /home/corona/workspace/simgrid/src/simix/smx_context_sysv.c:191
#13 0x00007ffff679cf60 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#14 0x0000000000000000 in ?? ()
</pre>

When running in parallel mode all worker threads can call the `SIMIX_process_cleanup()` concurrently which does things such as:

~~~c++
XBT_DEBUG("%p should not be run anymore",process);
xbt_swag_remove(process, simix_global->process_list);
xbt_swag_remove(process, SIMIX_host_priv(process->smx_host)->process_list);
xbt_swag_insert(process, simix_global->process_to_destroy);
~~~

The SWAG are modified concurrently by the worker threads  without synchronization. In some cases, they go into inconsistent states (for example, `swag->count` is no more consistent with the number of elements really in the swag).

The code above those lines might need synchronization as well.

Shall we just add some synchronization here or should this really be done in the maestro (and not in the workers)?

**Comment by randomstuff** [comment]
Fixed with a mutex.
